services:
    couchbase_cluster:
        class: CouchbaseCluster
        arguments:
            - url
            - cluster_authorization

    couchbase_generate_views_command:
        class: Apperturedev\CouchbaseBundle\Command\CouchbaseGenerateViewsCommand
        calls:
            - [ setContainer, [ "@service_container" ]]
        tags:
            - {name: console.command}

    couchbase:
        class: Apperturedev\CouchbaseBundle\Classes\CouchbaseORM
        arguments:
            - "@couchbase_cluster"
            - "@doctrine.orm.entity_manager"
            - "@jms_serializer"
            - bucket_array
