services:
    fredpalas.couchbase_bundle.exclusion_sequence:
        class: PhpCollection\Sequence
        public: false

    fredpalas.couchbase_bundle.exclusion_strategy:
        class: JMS\Serializer\Exclusion\DisjunctExclusionStrategy
        public: false
        arguments:
            - "@fredpalas.couchbase_bundle.exclusion_sequence"

    fredpalas.couchbase_bundle.couchbase_cluster:
        class: CouchbaseCluster
        public: false
        arguments:
            - '%couchbase_bundle.url%'
        calls:
            - [authenticateAs, ['%couchbase_bundle.user%', '%couchbase_bundle.password%']]

    fredpalas.couchbase_bundle.generate_views_command:
        class: Apperturedev\CouchbaseBundle\Command\CouchbaseGenerateViewsCommand
        arguments:
            - '@doctrine'
            - '@couchbase'
        tags:
            - {name: console.command}

    fredpalas.couchbase_bundle.generate_index_command:
        class: Apperturedev\CouchbaseBundle\Command\CouchbaseGenerateIndexCommand
        arguments:
            - '@couchbase'
        tags:
            - {name: console.command}

    couchbase:
        class: Apperturedev\CouchbaseBundle\Classes\CouchbaseORM
        arguments:
            - "@fredpalas.couchbase_bundle.couchbase_cluster"
            - "@doctrine.orm.entity_manager"
            - "@jms_serializer"
            - "@fredpalas.couchbase_bundle.exclusion_strategy"
            - 'default'
            - '%couchbase_bundle.buckets%'
